### ISSUE TITLE
Radarr not working?

### ISSUE THREAD

**Issue by harveywlong** [ngovil21/RequestChannel.bundle#55] opened 2017-02-19 17:21 UTC
I've configured with my API key and my profile settings and whatnot. I can search for the movie I wanna add but it doesn't get sent to Radarr and when I click the "Send to Radarr" it just gives me "Channel has stopped responding"

**Comment by ngovil21** [comment] 2017-02-20 03:04
Latest version of Radarr changed it's API and has stopped working. I am going to wait until the API is more settled before updating it.

**Comment by harveywlong** [comment] 2017-03-08 09:37
Thanks. I use radarr and prefer it highly over CP. Would love to know when you change it.

**Comment by Zordekai** [comment] 2017-03-14 18:46
Oh man I was pulling my hair out over this error. going to paste the error into the logs for those who might be googling it.

`2017-03-14 13:26:50,103 (7f50d5ffb700) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-03e4cfa35/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/RequestChannel.bundle/Contents/Code/Session.py", line 1517, in SendToRadarr
    rootFolderPath = root[0]['path']
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/RequestChannel.bundle/Contents/Code/Session.py", line 1574, in RadarrMovieExists
    if movie['id'] and (movie['imdbId'] == str(movie_id) or str(movie['tmdbId']) == str(movie_id)):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-03e4cfa35/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
TypeError: string indices must be integers, not str`

**Comment by arm3n** [comment] 2017-03-18 23:52
Also having issues with sending requests to Radarr.  Running on latest develop branch (49f8fd1 last commit).  I thought I read in another thread that you had this working a couple of weeks back?

Big fan of this project, thanks!

**Comment by ngovil21** [comment] 2017-03-19 02:55
Radarr is being constantly updated and the API isn't fixed, so I had Radarr working, but then they changed some things. With that said, the latest version of the channel should work with the lastest stable release of Radarr. Just merged the master to the development branch so that should work too based on my testing.

**Comment by arm3n** [comment] 2017-03-19 13:15
Thank you so much - I was able to get the Radarr integration to work.  Sure glad I put the effort in too - Radarr is so much more consistent compared to CouchPotato when it comes to retrieving nzbs.

Beer on its way 👍

**Closed** 2017-03-21 02:45 UTC

**Comment by theCheek** [comment] 2017-03-21 05:35
Thanks for this ngovil, much appreciated.

Found a small bug however - it seems that when 'TheMovieDatabase' is set in the bundle, Radarr requests don't get through, but they work with 'OpenMovieDatabase'.  Just a heads up.

**Comment by ngovil21** [comment] 2017-03-21 06:26
@theCheek Are you sure about that? I just tested both sources and they were working for me. If you can recreate the problem, send me a log to ngovil21@gmail.com.

**Comment by theCheek** [comment] 2017-03-21 06:42
sure mate I'll get on it when back from work. Maybe its a PEBCAK error on my side, but I'll double check.

**Comment by theCheek** [comment] 2017-03-23 21:22
never mind. Can't reproduce it, so guess something else was happening. Nothing to see here :)
