### ISSUE TITLE
Radarr - Channel Not Responding

### ISSUE THREAD

**Issue by moveit124** [ngovil21/RequestChannel.bundle#74] opened 2017-11-12 00:14 UTC
I am having issues with radarr specifically.  Sonarr works perfectly and adds requests and is able to be managed but radarr fails and says channel not responding.  When you go to manage request you can press the send to radarr button but it does the same thing as well.  Any known fix for this?  Or is it known already?

**Comment by ngovil21** [comment] 2017-11-20 14:57
Could you send a log to ngovil21@gmail.com?

**Comment by Deanosim1** [comment] 2017-12-23 02:54
I am also having this issue, I have attached the log file
[com.plexapp.plugins.plexrequestschannel.log](https://github.com/ngovil21/RequestChannel.bundle/files/1583811/com.plexapp.plugins.plexrequestschannel.log)

**Comment by Deanosim1** [comment] 2017-12-23 02:59
It would seem even though I've set the IP for radarr it's still using 127.0.0.1

> ERROR (networking:219) - Error opening URL 'http://127.0.0.1:7878/api/movie'

**Comment by ngovil21** [comment] 2017-12-24 05:07
@Deanosim1 please try restarting the Plex Server. Sometimes the settings are not re-configured until after a restart.

**Comment by khaledsebak** [comment] 2018-02-24 00:19
I'm having a similar issue, Sonarr works fine, Radarr is having isssues, service is running on the same machine
DEBUG (networking:166) - Requesting 'http://xxx.xxx.x.xx:7878/api/movie'
DEBUG (logkit:13) - Error in getMovies:

**Comment by ngovil21** [comment] 2018-03-02 04:41
@khaledsebak I'll need more of the error information if possible.

Could you send a log to ngovil21@gmail.com?

Refer to the Wiki for how to get a [here.](https://github.com/ngovil21/RequestChannel.bundle/wiki/How-to-get-Channel-Log)

**Comment by ngovil21** [comment] 2018-04-07 18:52
Should be fixed in the last update. Duplicate of #81.

**Closed by ngovil21** 2018-04-07 18:52 UTC
